# Generated by Django 2.2.7 on 2019-11-06 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('item', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('store', models.CharField(max_length=255)),
                ('purchaseDate', models.DateField()),
            ],
        ),
    ]
