# Generated by Django 2.2.7 on 2019-11-06 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PurchaseData',
            new_name='PurchaseTable',
        ),
    ]
