# Generated by Django 2.2.7 on 2019-11-06 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0002_auto_20191106_1434'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PurchaseTable',
            new_name='Purchases',
        ),
        migrations.RenameField(
            model_name='purchases',
            old_name='purchaseDate',
            new_name='purchase_Date',
        ),
    ]
