# Generated by Django 2.2.7 on 2019-11-06 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0003_auto_20191106_1949'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchases',
            old_name='purchase_Date',
            new_name='purchase_date',
        ),
    ]
